#!/usr/bin/env python3
"""
Turn confirmed.csv into an idempotent INSERT for Supabase public.job_sources.
Handles Workday's tenant|dc|site identifier (splits into slug/datacenter/site).

Usage:  python make_sql.py
Output: job_sources_insert.sql  (paste into the Supabase SQL editor)
"""
import csv, os

HERE = os.path.dirname(os.path.abspath(__file__))
IN = os.path.join(HERE, "confirmed.csv")
OUT = os.path.join(HERE, "job_sources_insert.sql")

rows, seen = [], set()
for r in csv.reader(open(IN, encoding="utf-8")):
    if len(r) < 2:
        continue
    plat, ident = r[0].strip(), r[1].strip()
    if plat == "workday":
        try:
            tenant, dc, site = ident.split("|")
        except ValueError:
            continue
        slug, datacenter, site = tenant, dc, site
    else:
        slug, datacenter, site = ident, None, None
    key = (plat, slug)
    if key in seen:
        continue
    seen.add(key)
    company = slug.replace("'", "''")
    rows.append((plat, slug.replace("'", "''"), company, datacenter, site))

with open(OUT, "w", encoding="utf-8") as f:
    f.write("-- Generated by discovery/make_sql.py - paste into the Supabase SQL editor.\n")
    f.write("-- Safe to re-run (on conflict do nothing).\n")
    f.write("insert into public.job_sources (platform, slug, company_name, datacenter, site) values\n")
    vals = []
    for p, slug, co, dc, site in rows:
        dc_s = f"'{dc}'" if dc else "null"
        site_s = f"'{site}'" if site else "null"
        vals.append(f"  ('{p}','{slug}','{co}',{dc_s},{site_s})")
    f.write(",\n".join(vals))
    f.write("\non conflict (platform, slug) do nothing;\n")

print(f"wrote {len(rows)} rows -> {OUT}")
