-- ============================================================================
-- GigCute -- job_sources bulk expansion (893 confirmed ATS boards)
-- Auto-generated from live-validated Greenhouse/Lever/Ashby slugs. Each was
-- confirmed to return >0 jobs at generation time. Dead/renamed boards are
-- harmless -- the ingest-jobs function skips any slug that errors.
-- Safe to re-run: ON CONFLICT (platform, slug) DO NOTHING.
-- ============================================================================
insert into public.job_sources (platform, slug, company_name) values

  ('ashby','1x','1x Technologies'),
  ('ashby','a16z-crypto','A16z Crypto'),
  ('ashby','abacum','Abacum'),
  ('ashby','abridge','Abridge'),
  ('ashby','absorblms','Absorb Lms'),
  ('ashby','addi','Addi'),
  ('ashby','aim','Aim'),
  ('ashby','airwallex','Airwallex'),
  ('ashby','alchemy','Alchemy'),
  ('ashby','alephalpha','Aleph Alpha'),
  ('ashby','allen-control-systems','Allen Control Systems'),
  ('ashby','ambiencehealthcare','Ambience Healthcare'),
  ('ashby','andela','Andela'),
  ('ashby','anrok','Anrok'),
  ('ashby','antimetal','Antimetal'),
  ('ashby','apollo-graphql','Apollo Graphql'),
  ('ashby','aptible','Aptible'),
  ('ashby','aqua-voice','Aqua Voice'),
  ('ashby','arthur-ai','Arthur Ai'),
  ('ashby','artisan','Artisan'),
  ('ashby','astra','Astra'),
  ('ashby','astronomer','Astronomer'),
  ('ashby','atlan','Atlan'),
  ('ashby','atomic','Atomic'),
  ('ashby','attention','Attention'),
  ('ashby','attio','Attio'),
  ('ashby','augur','Augur'),
  ('ashby','aurorasolar','Aurora Solar'),
  ('ashby','authzed','Authzed'),
  ('ashby','aviator','Aviator'),
  ('ashby','away','Away'),
  ('ashby','babbel','Babbel'),
  ('ashby','backpack','Backpack'),
  ('ashby','base','Base'),
  ('ashby','basecamp-research','Basecamp Research'),
  ('ashby','baseten','Baseten'),
  ('ashby','beacons','Beacons'),
  ('ashby','bedrockocean','Bedrock Ocean'),
  ('ashby','belvo','Belvo'),
  ('ashby','bestow','Bestow'),
  ('ashby','better-mortgage','Better Mortgage'),
  ('ashby','blacksmith','Blacksmith'),
  ('ashby','bland','Bland'),
  ('ashby','brainly','Brainly'),
  ('ashby','braintrust','Braintrust'),
  ('ashby','branchinsurance','Branch Insurance'),
  ('ashby','brigit','Brigit'),
  ('ashby','bubble','Bubble'),
  ('ashby','buffer','Buffer'),
  ('ashby','bunny','Bunny'),
  ('ashby','cambly','Cambly'),
  ('ashby','campfire','Campfire'),
  ('ashby','canvas-medical','Canvas Medical'),
  ('ashby','capchase','Capchase'),
  ('ashby','cartesia','Cartesia'),
  ('ashby','castle','Castle'),
  ('ashby','causal','Causal'),
  ('ashby','cerebras','Cerebras'),
  ('ashby','certn','Certn'),
  ('ashby','chaidiscovery','Chai Discovery'),
  ('ashby','charthop','Charthop'),
  ('ashby','chilipiper','Chili Piper'),
  ('ashby','circleback','Circleback'),
  ('ashby','claylabs','Clay Labs'),
  ('ashby','clearco','Clearco'),
  ('ashby','close','Close'),
  ('ashby','codat','Codat'),
  ('ashby','coder','Coder'),
  ('ashby','coderabbit','Coderabbit'),
  ('ashby','cognition','Cognition'),
  ('ashby','color-health','Color Health'),
  ('ashby','column','Column'),
  ('ashby','commonroom','Common Room'),
  ('ashby','commure','Commure'),
  ('ashby','copilot-money','Copilot Money'),
  ('ashby','corvus-robotics','Corvus Robotics'),
  ('ashby','cradlebio','Cradle Bio'),
  ('ashby','craftdocs','Craft Docs'),
  ('ashby','credal','Credal'),
  ('ashby','crisp','Crisp'),
  ('ashby','crusoe','Crusoe'),
  ('ashby','cruxclimate','Crux Climate'),
  ('ashby','cube','Cube'),
  ('ashby','cubesoftware','Cube Software'),
  ('ashby','cursor','Cursor'),
  ('ashby','dapper','Dapper Labs'),
  ('ashby','datafold','Datafold'),
  ('ashby','dave','Dave'),
  ('ashby','decagon','Decagon'),
  ('ashby','deepgram','Deepgram'),
  ('ashby','deepnote','Deepnote'),
  ('ashby','delinea','Delinea'),
  ('ashby','demandbase','Demandbase'),
  ('ashby','depot','Depot'),
  ('ashby','distributed-spectrum','Distributed Spectrum'),
  ('ashby','docebo','Docebo'),
  ('ashby','dovetail','Dovetail'),
  ('ashby','duckbill','Duckbill Group'),
  ('ashby','dune','Dune'),
  ('ashby','e2b','E2b'),
  ('ashby','elevenlabs','Elevenlabs'),
  ('ashby','elliptic','Elliptic'),
  ('ashby','encord','Encord'),
  ('ashby','endgame','Endgame'),
  ('ashby','etched','Etched'),
  ('ashby','every-io','Every Io'),
  ('ashby','fal-ai','Fal Ai'),
  ('ashby','fathom','Fathom'),
  ('ashby','fiddler-ai','Fiddler Ai'),
  ('ashby','finout','Finout'),
  ('ashby','flink','Flink'),
  ('ashby','forma','Forma'),
  ('ashby','formal','Formal'),
  ('ashby','formenergy','Form Energy'),
  ('ashby','forto','Forto'),
  ('ashby','foundation','Foundation'),
  ('ashby','foursquare','Foursquare'),
  ('ashby','freetrade','Freetrade'),
  ('ashby','freshpaint','Freshpaint'),
  ('ashby','gamma','Gamma'),
  ('ashby','gecko-robotics','Gecko Robotics'),
  ('ashby','genomics','Genomics'),
  ('ashby','gitbook','Gitbook'),
  ('ashby','gooddata','Gooddata'),
  ('ashby','gorgias','Gorgias'),
  ('ashby','gradient','Gradient Labs'),
  ('ashby','gradient-labs','Gradient Labs'),
  ('ashby','granola','Granola'),
  ('ashby','graphitehq','Graphite Hq'),
  ('ashby','greatquestion','Great Question'),
  ('ashby','greptile','Greptile'),
  ('ashby','grow-therapy','Grow Therapy'),
  ('ashby','gumloop','Gumloop'),
  ('ashby','harvey','Harvey'),
  ('ashby','havocai','Havoc Ai'),
  ('ashby','hcompany','H Company'),
  ('ashby','headway','Headway'),
  ('ashby','helm-ai','Helm Ai'),
  ('ashby','helpscout','Help Scout'),
  ('ashby','highbeam','Highbeam'),
  ('ashby','hinge-health','Hinge Health'),
  ('ashby','homebase','Homebase'),
  ('ashby','hopper','Hopper'),
  ('ashby','horizon3ai','Horizon3 Ai'),
  ('ashby','hyperbolic','Hyperbolic'),
  ('ashby','hyperscience','Hyperscience'),
  ('ashby','iambic-therapeutics','Iambic Therapeutics'),
  ('ashby','iceye','Iceye'),
  ('ashby','impossible-foods','Impossible Foods'),
  ('ashby','influxdata','Influxdata'),
  ('ashby','inngest','Inngest'),
  ('ashby','insitro','Insitro'),
  ('ashby','interview-kickstart','Interview Kickstart'),
  ('ashby','isometric','Isometric'),
  ('ashby','josys','Josys'),
  ('ashby','juro','Juro'),
  ('ashby','kestra','Kestra'),
  ('ashby','kindred','Kindred'),
  ('ashby','kit','Kit'),
  ('ashby','kittl','Kittl'),
  ('ashby','kiwi','Kiwi'),
  ('ashby','kong','Kong'),
  ('ashby','kueski','Kueski'),
  ('ashby','kustomer','Kustomer'),
  ('ashby','lago','Lago'),
  ('ashby','lambda','Lambda Labs'),
  ('ashby','lancedb','Lancedb'),
  ('ashby','langchain','Langchain'),
  ('ashby','langdock','Langdock'),
  ('ashby','langfuse','Langfuse'),
  ('ashby','latchbio','Latch Bio'),
  ('ashby','latent','Latent Labs'),
  ('ashby','latentlabs','Latent Labs'),
  ('ashby','leapsome','Leapsome'),
  ('ashby','lemfi','Lemfi'),
  ('ashby','lemlist','Lemlist'),
  ('ashby','lemonade','Lemonade'),
  ('ashby','lendable','Lendable'),
  ('ashby','level-ai','Level Ai'),
  ('ashby','levelpath','Levelpath'),
  ('ashby','light','Light'),
  ('ashby','lightdash','Lightdash'),
  ('ashby','lightspeed','Lightspeed'),
  ('ashby','llamaindex','Llamaindex'),
  ('ashby','loora','Loora'),
  ('ashby','lorikeet','Lorikeet'),
  ('ashby','lumos','Lumos'),
  ('ashby','magiceden','Magic Eden'),
  ('ashby','mangomint','Mangomint'),
  ('ashby','materialize','Materialize'),
  ('ashby','materialsecurity','Material Security'),
  ('ashby','matter-labs','Matter Labs'),
  ('ashby','maven','Maven'),
  ('ashby','maven-agi','Maven Agi'),
  ('ashby','meow','Meow'),
  ('ashby','mercor','Mercor'),
  ('ashby','merge','Merge'),
  ('ashby','metriport','Metriport'),
  ('ashby','middesk','Middesk'),
  ('ashby','mintlify','Mintlify'),
  ('ashby','moderntreasury','Modern Treasury'),
  ('ashby','mollie','Mollie'),
  ('ashby','monarchmoney','Monarch Money'),
  ('ashby','motherduck','Motherduck'),
  ('ashby','mural','Mural'),
  ('ashby','mutiny','Mutiny'),
  ('ashby','mux','Mux'),
  ('ashby','mystenlabs','Mysten Labs'),
  ('ashby','n8n','N8n'),
  ('ashby','nabla','Nabla'),
  ('ashby','namespace','Namespace'),
  ('ashby','nango','Nango'),
  ('ashby','nava-benefits','Nava Benefits'),
  ('ashby','navi','Navi'),
  ('ashby','nightfall-ai','Nightfall Ai'),
  ('ashby','novo','Novo'),
  ('ashby','numeral','Numeral'),
  ('ashby','numeric','Numeric'),
  ('ashby','nylas','Nylas'),
  ('ashby','omni','Omni'),
  ('ashby','opal','Opal'),
  ('ashby','opensea','Opensea'),
  ('ashby','orb','Orb'),
  ('ashby','orum','Orum'),
  ('ashby','oso','Oso'),
  ('ashby','overjet','Overjet'),
  ('ashby','paddle','Paddle'),
  ('ashby','paireyewear','Pair Eyewear'),
  ('ashby','parafin','Parafin'),
  ('ashby','paragon','Paragon'),
  ('ashby','partiful','Partiful'),
  ('ashby','passage','Passage'),
  ('ashby','passes','Passes'),
  ('ashby','patreon','Patreon'),
  ('ashby','paxos','Paxos'),
  ('ashby','payabli','Payabli'),
  ('ashby','pearl','Pearl'),
  ('ashby','periodic-labs','Periodic Labs'),
  ('ashby','persona','Persona'),
  ('ashby','phantom','Phantom'),
  ('ashby','phoenix','Phoenix Labs'),
  ('ashby','phonic','Phonic'),
  ('ashby','photoroom','Photoroom'),
  ('ashby','physicalintelligence','Physical Intelligence'),
  ('ashby','pinecone','Pinecone'),
  ('ashby','plain','Plain'),
  ('ashby','plane','Plane'),
  ('ashby','pleo','Pleo'),
  ('ashby','polymarket','Polymarket'),
  ('ashby','poolside','Poolside'),
  ('ashby','posh','Posh'),
  ('ashby','possible-finance','Possible Finance'),
  ('ashby','posthog','Posthog'),
  ('ashby','prefect','Prefect'),
  ('ashby','preply','Preply'),
  ('ashby','primeintellect','Prime Intellect'),
  ('ashby','primer','Primer'),
  ('ashby','propel','Propel'),
  ('ashby','prophet-security','Prophet Security'),
  ('ashby','prose','Prose'),
  ('ashby','pylon','Pylon'),
  ('ashby','qualified','Qualified'),
  ('ashby','quicknode','Quicknode'),
  ('ashby','railway','Railway'),
  ('ashby','rain','Rain'),
  ('ashby','rasa','Rasa'),
  ('ashby','read-ai','Read Ai'),
  ('ashby','readme','Readme'),
  ('ashby','real','Real'),
  ('ashby','recraft','Recraft'),
  ('ashby','reducto','Reducto'),
  ('ashby','regard','Regard'),
  ('ashby','relayfi','Relay Fi'),
  ('ashby','relevanceai','Relevance Ai'),
  ('ashby','render','Render'),
  ('ashby','replicant','Replicant'),
  ('ashby','resend','Resend'),
  ('ashby','restream','Restream'),
  ('ashby','retell-ai','Retell Ai'),
  ('ashby','revenuecat','Revenuecat'),
  ('ashby','rho','Rho'),
  ('ashby','rillet','Rillet'),
  ('ashby','rime','Rime'),
  ('ashby','robin-ai','Robin Ai'),
  ('ashby','roboflow','Roboflow'),
  ('ashby','rothys','Rothys'),
  ('ashby','rula','Rula'),
  ('ashby','runpod','Runpod'),
  ('ashby','runway','Runway'),
  ('ashby','rutter','Rutter'),
  ('ashby','sandboxaq','Sandboxaq'),
  ('ashby','sardine','Sardine'),
  ('ashby','saronic','Saronic'),
  ('ashby','scalar','Scalar'),
  ('ashby','seconddinner','Second Dinner'),
  ('ashby','semgrep','Semgrep'),
  ('ashby','semperis','Semperis'),
  ('ashby','sensor-tower','Sensor Tower'),
  ('ashby','sentilink','Sentilink'),
  ('ashby','sentra','Sentra'),
  ('ashby','sentry','Sentry'),
  ('ashby','seon','Seon'),
  ('ashby','sequence','Sequence'),
  ('ashby','sequoia','Sequoia'),
  ('ashby','serverobotics','Serve Robotics'),
  ('ashby','sierra','Sierra'),
  ('ashby','sifflet','Sifflet'),
  ('ashby','sift','Sift'),
  ('ashby','singular','Singular'),
  ('ashby','skydio','Skydio'),
  ('ashby','skymavis','Sky Mavis'),
  ('ashby','sleeper','Sleeper'),
  ('ashby','slingshot-aerospace','Slingshot Aerospace'),
  ('ashby','socure','Socure'),
  ('ashby','solanalabs','Solana Labs'),
  ('ashby','solidgate','Solidgate'),
  ('ashby','sondermind','Sondermind'),
  ('ashby','sorare','Sorare'),
  ('ashby','speak','Speak'),
  ('ashby','speakeasy','Speakeasy'),
  ('ashby','spotdraft','Spotdraft'),
  ('ashby','spoton','Spoton'),
  ('ashby','sprig','Sprig'),
  ('ashby','stack-ai','Stack Ai'),
  ('ashby','stytch','Stytch'),
  ('ashby','substack','Substack'),
  ('ashby','succinct','Succinct'),
  ('ashby','suno','Suno'),
  ('ashby','supabase','Supabase'),
  ('ashby','supercell','Supercell'),
  ('ashby','swap','Swap'),
  ('ashby','sweep','Sweep'),
  ('ashby','sylvera','Sylvera'),
  ('ashby','synctera','Synctera'),
  ('ashby','synthesia','Synthesia'),
  ('ashby','synthflow','Synthflow'),
  ('ashby','tabs','Tabs'),
  ('ashby','temporal','Temporal'),
  ('ashby','tenjin','Tenjin'),
  ('ashby','tennr','Tennr'),
  ('ashby','titan','Titan'),
  ('ashby','tldraw','Tldraw'),
  ('ashby','todyl','Todyl'),
  ('ashby','tomo','Tomo'),
  ('ashby','trm-labs','Trm Labs'),
  ('ashby','trulioo','Trulioo'),
  ('ashby','turbopuffer','Turbopuffer'),
  ('ashby','turion-space','Turion Space'),
  ('ashby','twelve','Twelve Labs'),
  ('ashby','twelve-labs','Twelve Labs'),
  ('ashby','uniswap','Uniswap Labs'),
  ('ashby','unit','Unit'),
  ('ashby','unstructured','Unstructured'),
  ('ashby','valon','Valon'),
  ('ashby','vantage','Vantage'),
  ('ashby','vapi','Vapi'),
  ('ashby','variant-fund','Variant Fund'),
  ('ashby','vastai','Vast Ai'),
  ('ashby','vaulted-deep','Vaulted Deep'),
  ('ashby','vellum','Vellum'),
  ('ashby','verisoul','Verisoul'),
  ('ashby','virtahealth','Virta Health'),
  ('ashby','vultr','Vultr'),
  ('ashby','wayflyer','Wayflyer'),
  ('ashby','weaviate','Weaviate'),
  ('ashby','windmill','Windmill'),
  ('ashby','wisp','Wisp'),
  ('ashby','wistia','Wistia'),
  ('ashby','workos','Workos'),
  ('ashby','writer','Writer'),
  ('ashby','wundergraph','Wundergraph'),
  ('ashby','zilch','Zilch'),
  ('ashby','zip','Zip'),
  ('greenhouse','6sense','6sense'),
  ('greenhouse','7shifts','7shifts'),
  ('greenhouse','abnormalsecurity','Abnormal Security'),
  ('greenhouse','adyen','Adyen'),
  ('greenhouse','ag1','Ag1'),
  ('greenhouse','agilityrobotics','Agility Robotics'),
  ('greenhouse','aha','Aha'),
  ('greenhouse','airship','Airship'),
  ('greenhouse','albedo','Albedo'),
  ('greenhouse','allencontrolsystems','Allen Control Systems'),
  ('greenhouse','alloy','Alloy'),
  ('greenhouse','alma','Alma'),
  ('greenhouse','aloyoga','Alo Yoga'),
  ('greenhouse','alpaca','Alpaca'),
  ('greenhouse','altoslabs','Altos Labs'),
  ('greenhouse','altruist','Altruist'),
  ('greenhouse','amwell','Amwell'),
  ('greenhouse','antora','Antora'),
  ('greenhouse','apiiro','Apiiro'),
  ('greenhouse','apolloio','Apollo Io'),
  ('greenhouse','applovin','App", "lovin'),
  ('greenhouse','apptronik','Apptronik'),
  ('greenhouse','aptoslabs','Aptos Labs'),
  ('greenhouse','arizeai','Arize Ai'),
  ('greenhouse','arkoselabs','Arkose Labs'),
  ('greenhouse','array','Array Labs'),
  ('greenhouse','arvaintelligence','Arva Intelligence'),
  ('greenhouse','assemblyai','Assemblyai'),
  ('greenhouse','atoms','Atoms'),
  ('greenhouse','aurorainnovation','Aurora Innovation'),
  ('greenhouse','avride','Avride'),
  ('greenhouse','aweber','Aweber'),
  ('greenhouse','axiom','Axiom'),
  ('greenhouse','bandwidth','Bandwidth'),
  ('greenhouse','banyaninfrastructure','Banyan Infrastructure'),
  ('greenhouse','baselayer','Baselayer'),
  ('greenhouse','beam','Beam'),
  ('greenhouse','beautifulai','Beautiful Ai'),
  ('greenhouse','bellroy','Bellroy'),
  ('greenhouse','betterment','Betterment'),
  ('greenhouse','beyondtrust','Beyondtrust'),
  ('greenhouse','bigid','Bigid'),
  ('greenhouse','biofourmis','Biofourmis'),
  ('greenhouse','bishopfox','Bishop Fox'),
  ('greenhouse','bitgo','Bitgo'),
  ('greenhouse','bitpanda','Bitpanda'),
  ('greenhouse','blockrenovation','Block Renovation'),
  ('greenhouse','bloomreach','Bloomreach'),
  ('greenhouse','blumira','Blumira'),
  ('greenhouse','bombora','Bombora'),
  ('greenhouse','botauto','Bot Auto'),
  ('greenhouse','boulevard','Boulevard'),
  ('greenhouse','branchmetrics','Branch Metrics'),
  ('greenhouse','brave','Brave'),
  ('greenhouse','britive','Britive'),
  ('greenhouse','brooklinen','Brooklinen'),
  ('greenhouse','buildkite','Buildkite'),
  ('greenhouse','businessolver','Businessolver'),
  ('greenhouse','c6bank','C6 Bank'),
  ('greenhouse','calahealth','Cala Health'),
  ('greenhouse','capacity','Capacity'),
  ('greenhouse','capellaspace','Capella Space'),
  ('greenhouse','carbon','Carbon'),
  ('greenhouse','carbonfuture','Carbonfuture'),
  ('greenhouse','carbonrobotics','Carbon Robotics'),
  ('greenhouse','carrotfertility','Carrot Fertility'),
  ('greenhouse','castlery','Castlery'),
  ('greenhouse','catonetworks','Cato Networks'),
  ('greenhouse','celonis','Celonis'),
  ('greenhouse','cerebral','Cerebral'),
  ('greenhouse','chainguard','Chainguard'),
  ('greenhouse','chaosindustries','Chaos Industries'),
  ('greenhouse','charliehealth','Charlie Health'),
  ('greenhouse','circleso','Circle So'),
  ('greenhouse','clara','Clara'),
  ('greenhouse','clear','Clear'),
  ('greenhouse','cloverhealth','Clover Health'),
  ('greenhouse','cloverly','Cloverly'),
  ('greenhouse','coalition','Coalition'),
  ('greenhouse','cognism','Cognism'),
  ('greenhouse','collectivehealth','Collective Health'),
  ('greenhouse','collibra','Collibra'),
  ('greenhouse','consensys','Consensys'),
  ('greenhouse','constantcontact','Constant Contact'),
  ('greenhouse','cookunity','Cookunity'),
  ('greenhouse','corelight','Corelight'),
  ('greenhouse','coreweave','Coreweave'),
  ('greenhouse','counterpart','Counterpart'),
  ('greenhouse','coursera','Coursera'),
  ('greenhouse','cresta','Cresta'),
  ('greenhouse','cribl','Cribl'),
  ('greenhouse','cultureamp','Culture Amp'),
  ('greenhouse','current','Current'),
  ('greenhouse','cuyana','Cuyana'),
  ('greenhouse','cymulate','Cymulate'),
  ('greenhouse','datacamp','Datacamp'),
  ('greenhouse','dataiku','Dataiku'),
  ('greenhouse','daybreakhealth','Daybreak Health'),
  ('greenhouse','descope','Descope'),
  ('greenhouse','descript','Descript'),
  ('greenhouse','dexory','Dexory'),
  ('greenhouse','dialpad','Dialpad'),
  ('greenhouse','disco','Disco'),
  ('greenhouse','divergent','Divergent'),
  ('greenhouse','dominodatalab','Domino Data Lab'),
  ('greenhouse','dremio','Dremio'),
  ('greenhouse','drivewealth','Drivewealth'),
  ('greenhouse','duolingo','Duolingo'),
  ('greenhouse','dynotherapeutics','Dyno Therapeutics'),
  ('greenhouse','earnin','Earnin'),
  ('greenhouse','ebanx','Ebanx'),
  ('greenhouse','employeenavigator','Employee Navigator'),
  ('greenhouse','endorlabs','Endor Labs'),
  ('greenhouse','enterpret','Enterpret'),
  ('greenhouse','epicgames','Epic Games'),
  ('greenhouse','epirus','Epirus'),
  ('greenhouse','ess','Ess Inc'),
  ('greenhouse','esusu','Esusu'),
  ('greenhouse','ethoslife','Ethos Life'),
  ('greenhouse','everlaw','Everlaw'),
  ('greenhouse','expel','Expel'),
  ('greenhouse','factorialenergy','Factorial Energy'),
  ('greenhouse','fairmarkit','Fairmarkit'),
  ('greenhouse','fanduel','Fanduel'),
  ('greenhouse','fastspring','Fastspring'),
  ('greenhouse','figureai','Figure Ai'),
  ('greenhouse','fingerprint','Fingerprint'),
  ('greenhouse','fireblocks','Fireblocks'),
  ('greenhouse','fireworksai','Fireworks Ai'),
  ('greenhouse','flex','Flex'),
  ('greenhouse','flexe','Flexe'),
  ('greenhouse','flip','Flip'),
  ('greenhouse','flodesk','Flodesk'),
  ('greenhouse','folxhealth','Folx Health'),
  ('greenhouse','formic','Formic'),
  ('greenhouse','forter','Forter'),
  ('greenhouse','forward','Forward'),
  ('greenhouse','found','Found'),
  ('greenhouse','fourkites','Fourkites'),
  ('greenhouse','freenome','Freenome'),
  ('greenhouse','galileo','Galileo'),
  ('greenhouse','gatherai','Gather Ai'),
  ('greenhouse','gemini','Gemini'),
  ('greenhouse','generalassembly','General Assembly'),
  ('greenhouse','generatebiomedicines','Generate Biomedicines'),
  ('greenhouse','gensyn','Gensyn'),
  ('greenhouse','ghost','Ghost'),
  ('greenhouse','ginkgobioworks','Ginkgo Bioworks'),
  ('greenhouse','glide','Glide'),
  ('greenhouse','glossier','Glossier'),
  ('greenhouse','gocardless','Gocardless'),
  ('greenhouse','gongio','Gong Io'),
  ('greenhouse','goodr','Goodr'),
  ('greenhouse','graphcore','Graphcore'),
  ('greenhouse','grey','Grey'),
  ('greenhouse','group14','Group14'),
  ('greenhouse','guild','The Guild'),
  ('greenhouse','gymshark','Gymshark'),
  ('greenhouse','hackerrank','Hackerrank'),
  ('greenhouse','hawkeye360','Hawkeye 360'),
  ('greenhouse','hiddenlayer','Hiddenlayer'),
  ('greenhouse','highnote','Highnote'),
  ('greenhouse','homeward','Homeward'),
  ('greenhouse','honeycomb','Honeycomb'),
  ('greenhouse','hootsuite','Hootsuite'),
  ('greenhouse','humaninterest','Human Interest'),
  ('greenhouse','humeai','Hume Ai'),
  ('greenhouse','hungryroot','Hungryroot'),
  ('greenhouse','huntress','Huntress'),
  ('greenhouse','hypr','Hypr'),
  ('greenhouse','imbue','Imbue'),
  ('greenhouse','imply','Imply'),
  ('greenhouse','inceptive','Inceptive'),
  ('greenhouse','incode','Incode'),
  ('greenhouse','insider','Insider'),
  ('greenhouse','instabase','Instabase'),
  ('greenhouse','insurify','Insurify'),
  ('greenhouse','inter','Inter'),
  ('greenhouse','intercom','Intercom'),
  ('greenhouse','interviewkickstart','Interview Kickstart'),
  ('greenhouse','inversionspace','Inversion Space'),
  ('greenhouse','invisible','Invisible'),
  ('greenhouse','invoca','Invoca'),
  ('greenhouse','ionq','Ionq'),
  ('greenhouse','isomorphiclabs','Isomorphic Labs'),
  ('greenhouse','justworks','Justworks'),
  ('greenhouse','kairospower','Kairos Power'),
  ('greenhouse','kalshi','Kalshi'),
  ('greenhouse','kayak','Kayak'),
  ('greenhouse','keepersecurity','Keeper Security'),
  ('greenhouse','khanacademy','Khan Academy'),
  ('greenhouse','kikoff','Kikoff'),
  ('greenhouse','knit','Knit'),
  ('greenhouse','knock','Knock'),
  ('greenhouse','labelbox','Labelbox'),
  ('greenhouse','later','Later'),
  ('greenhouse','learnupon','Learnupon'),
  ('greenhouse','ledgy','Ledgy'),
  ('greenhouse','liftoff','Liftoff'),
  ('greenhouse','lightmatter','Lightmatter'),
  ('greenhouse','lightningai','Lightning Ai'),
  ('greenhouse','lilasciences','Lila Sciences'),
  ('greenhouse','listrak','Listrak'),
  ('greenhouse','lithic','Lithic'),
  ('greenhouse','litify','Litify'),
  ('greenhouse','mavenclinic','Maven Clinic'),
  ('greenhouse','maymobility','May Mobility'),
  ('greenhouse','melio','Melio'),
  ('greenhouse','meruhealth','Meru Health'),
  ('greenhouse','metaphore','Metaphore'),
  ('greenhouse','metronome','Metronome'),
  ('greenhouse','mindbody','Mindbody'),
  ('greenhouse','misfitsmarket','Misfits Market'),
  ('greenhouse','missionlane','Mission Lane'),
  ('greenhouse','mixmax','Mixmax'),
  ('greenhouse','modernhealth','Modern Health'),
  ('greenhouse','moniepoint','Moniepoint'),
  ('greenhouse','moon','Moon'),
  ('greenhouse','motional','Motional'),
  ('greenhouse','movableink','Movable Ink'),
  ('greenhouse','muonspace','Muon Space'),
  ('greenhouse','n26','N26'),
  ('greenhouse','nanonets','Nanonets'),
  ('greenhouse','nansen','Nansen'),
  ('greenhouse','neo4j','Neo4j'),
  ('greenhouse','netskope','Netskope'),
  ('greenhouse','newlimit','Newlimit'),
  ('greenhouse','nexhealth','Nexhealth'),
  ('greenhouse','nextdoor','Nextdoor'),
  ('greenhouse','nimblerobotics','Nimble Robotics'),
  ('greenhouse','nooks','Nooks'),
  ('greenhouse','oasissecurity','Oasis Security'),
  ('greenhouse','obligo','Obligo'),
  ('greenhouse','observeai','Observe Ai'),
  ('greenhouse','octave','Octave'),
  ('greenhouse','octopusdeploy','Octopus Deploy'),
  ('greenhouse','oklo','Oklo'),
  ('greenhouse','omadahealth','Omada Health'),
  ('greenhouse','onemedical','One Medical'),
  ('greenhouse','onrunning','On Running'),
  ('greenhouse','openly','Openly'),
  ('greenhouse','opentable','Opentable'),
  ('greenhouse','oportun','Oportun'),
  ('greenhouse','orcasecurity','Orca Security'),
  ('greenhouse','orchard','Orchard'),
  ('greenhouse','otterai','Otter Ai'),
  ('greenhouse','outschool','Outschool'),
  ('greenhouse','pacaso','Pacaso'),
  ('greenhouse','pagerduty','Pagerduty'),
  ('greenhouse','palmetto','Palmetto'),
  ('greenhouse','pandadoc','Pandadoc'),
  ('greenhouse','parachutehome','Parachute Home'),
  ('greenhouse','paradigm','Paradigm'),
  ('greenhouse','parloa','Parloa'),
  ('greenhouse','pathai','Pathai'),
  ('greenhouse','pathrobotics','Path Robotics'),
  ('greenhouse','paystack','Paystack'),
  ('greenhouse','paytient','Paytient'),
  ('greenhouse','peakdesign','Peak Design'),
  ('greenhouse','phonepe','Phonepe'),
  ('greenhouse','pieinsurance','Pie Insurance'),
  ('greenhouse','pingidentity','Pingidentity'),
  ('greenhouse','platformsh','Platformsh'),
  ('greenhouse','polyai','Poly Ai'),
  ('greenhouse','postscript','Postscript'),
  ('greenhouse','prisma','Prisma'),
  ('greenhouse','privateer','Privateer'),
  ('greenhouse','prizepicks','Prizepicks'),
  ('greenhouse','project44','Project44'),
  ('greenhouse','prolific','Prolific'),
  ('greenhouse','proof','Proof'),
  ('greenhouse','prove','Prove'),
  ('greenhouse','psiquantum','Psiquantum'),
  ('greenhouse','public','Public'),
  ('greenhouse','pubnub','Pubnub'),
  ('greenhouse','quaise','Quaise'),
  ('greenhouse','quintoandar','Quintoandar'),
  ('greenhouse','qventus','Qventus'),
  ('greenhouse','raisin','Raisin'),
  ('greenhouse','raven','Raven'),
  ('greenhouse','rdstation','Rd Station'),
  ('greenhouse','recordedfuture','Recorded Future'),
  ('greenhouse','recursionpharmaceuticals','Recursion Pharmaceuticals'),
  ('greenhouse','redwoodmaterials','Redwood Materials'),
  ('greenhouse','regie','Regie'),
  ('greenhouse','relativity','Relativity'),
  ('greenhouse','riotgames','Riot Games'),
  ('greenhouse','riskified','Riskified'),
  ('greenhouse','ritual','Ritual'),
  ('greenhouse','riverlane','Riverlane'),
  ('greenhouse','roblox','Roblox'),
  ('greenhouse','rocketlab','Rocket Lab'),
  ('greenhouse','rocketlawyer','Rocket Lawyer'),
  ('greenhouse','roka','Roka'),
  ('greenhouse','rondoenergy','Rondo Energy'),
  ('greenhouse','roofstock','Roofstock'),
  ('greenhouse','ruggable','Ruggable'),
  ('greenhouse','saatva','Saatva'),
  ('greenhouse','safebreach','Safebreach'),
  ('greenhouse','sagesure','Sagesure'),
  ('greenhouse','salesloft','Salesloft'),
  ('greenhouse','saltsecurity','Salt Security'),
  ('greenhouse','scopely','Scopely'),
  ('greenhouse','seamlessai','Seamless Ai'),
  ('greenhouse','seatgeek','Seatgeek'),
  ('greenhouse','seed','Seed'),
  ('greenhouse','selffinancial','Self Financial'),
  ('greenhouse','senrasystems','Senra Systems'),
  ('greenhouse','sezzle','Sezzle'),
  ('greenhouse','sigmacomputing','Sigma Computing'),
  ('greenhouse','silananotechnologies','Sila Nanotechnologies'),
  ('greenhouse','singlestore','Singlestore'),
  ('greenhouse','singularity6','Singularity6'),
  ('greenhouse','sisense','Sisense'),
  ('greenhouse','skyscanner','Skyscanner'),
  ('greenhouse','slingshotaerospace','Slingshot Aerospace'),
  ('greenhouse','smartsheet','Smartsheet'),
  ('greenhouse','snorkelai','Snorkel Ai'),
  ('greenhouse','socket','Socket'),
  ('greenhouse','solidpower','Solid Power'),
  ('greenhouse','springboard','Springboard'),
  ('greenhouse','sproutsocial','Sprout Social'),
  ('greenhouse','stackav','Stack Av'),
  ('greenhouse','starburst','Starburst'),
  ('greenhouse','stone','Stone'),
  ('greenhouse','strivehealth','Strive Health'),
  ('greenhouse','suki','Suki'),
  ('greenhouse','sumup','Sumup'),
  ('greenhouse','superai','Super Ai'),
  ('greenhouse','superset','Superset'),
  ('greenhouse','sweetsecurity','Sweet Security'),
  ('greenhouse','tavily','Tavily'),
  ('greenhouse','tebra','Tebra'),
  ('greenhouse','tenstorrent','Tenstorrent'),
  ('greenhouse','terraquantum','Terra Quantum'),
  ('greenhouse','thatch','Thatch'),
  ('greenhouse','thinkific','Thinkific'),
  ('greenhouse','thirtymadison','Thirty Madison'),
  ('greenhouse','threatlocker','Threatlocker'),
  ('greenhouse','thrivemarket','Thrive Market'),
  ('greenhouse','tia','Tia'),
  ('greenhouse','toast','Toast'),
  ('greenhouse','togetherai','Together Ai'),
  ('greenhouse','touchbistro','Touchbistro'),
  ('greenhouse','transmitsecurity','Transmit Security'),
  ('greenhouse','tripactions','Tripactions'),
  ('greenhouse','tripadvisor','Tripadvisor'),
  ('greenhouse','tripledotstudios','Tripledot Studios'),
  ('greenhouse','truefoundry','Truefoundry'),
  ('greenhouse','truelayer','Truelayer'),
  ('greenhouse','truveta','Truveta'),
  ('greenhouse','turbotenant','Turbotenant'),
  ('greenhouse','turing','Turing'),
  ('greenhouse','twochairs','Two Chairs'),
  ('greenhouse','typeface','Typeface'),
  ('greenhouse','uberfreight','Uber Freight'),
  ('greenhouse','udacity','Udacity'),
  ('greenhouse','udemy','Udemy'),
  ('greenhouse','udio','Udio'),
  ('greenhouse','underdogfantasy','Underdog Fantasy'),
  ('greenhouse','uniteus','Unite Us'),
  ('greenhouse','upgrade','Upgrade'),
  ('greenhouse','ursamajor','Ursa Major'),
  ('greenhouse','usergems','Usergems'),
  ('greenhouse','valerahealth','Valera Health'),
  ('greenhouse','valohealth','Valo Health'),
  ('greenhouse','vannevarlabs','Vannevar Labs'),
  ('greenhouse','vardaspace','Varda Space'),
  ('greenhouse','veranahealth','Verana Health'),
  ('greenhouse','veriff','Veriff'),
  ('greenhouse','vestwell','Vestwell'),
  ('greenhouse','vonage','Vonage'),
  ('greenhouse','vtex','Vtex'),
  ('greenhouse','watershed','Watershed'),
  ('greenhouse','wayve','Wayve'),
  ('greenhouse','weave','Weave'),
  ('greenhouse','weee','Weee'),
  ('greenhouse','whop','Whop'),
  ('greenhouse','wildlifestudios','Wildlife Studios'),
  ('greenhouse','wing','Wing'),
  ('greenhouse','wisetack','Wisetack'),
  ('greenhouse','workato','Workato'),
  ('greenhouse','workboard','Workboard'),
  ('greenhouse','wrike','Wrike'),
  ('greenhouse','xairatherapeutics','Xaira Therapeutics'),
  ('greenhouse','youcom','You Com'),
  ('greenhouse','yubico','Yubico'),
  ('greenhouse','yugabyte','Yugabyte'),
  ('greenhouse','zencoder','Zencoder'),
  ('greenhouse','zennioptical','Zenni Optical'),
  ('greenhouse','zenvia','Zenvia'),
  ('greenhouse','zestyai','Zesty Ai'),
  ('greenhouse','zetaglobal','Zeta Global'),
  ('greenhouse','zocdoc','Zocdoc'),
  ('greenhouse','zoominfo','Zoominfo'),
  ('greenhouse','zscaler','Zscaler'),
  ('lever','15five','15five'),
  ('lever','360learning','360learning'),
  ('lever','acceldata','Acceldata'),
  ('lever','activecampaign','Activecampaign'),
  ('lever','agiloft','Agiloft'),
  ('lever','agtonomy','Agtonomy'),
  ('lever','aircall','Aircall'),
  ('lever','alice-bob','Alice Bob'),
  ('lever','ambirobotics','Ambi Robotics'),
  ('lever','anchorage','Anchorage'),
  ('lever','angellist','Angellist'),
  ('lever','animocabrands','Animoca Brands'),
  ('lever','anyscale','Anyscale'),
  ('lever','arbitrumfoundation','Arbitrum Foundation'),
  ('lever','ataccama','Ataccama'),
  ('lever','atomcomputing','Atom Computing'),
  ('lever','baselane','Baselane'),
  ('lever','basis','Basis'),
  ('lever','betr','Betr'),
  ('lever','bis','Béis'),
  ('lever','brevo','Brevo'),
  ('lever','brightmachines','Bright Machines'),
  ('lever','brooksrunning','Brooks Running'),
  ('lever','buckmason','Buck Mason'),
  ('lever','canvasmedical','Canvas Medical'),
  ('lever','celestia','Celestia'),
  ('lever','charmindustrial','Charm Industrial'),
  ('lever','cloudinary','Cloudinary'),
  ('lever','cloudwalk','Cloudwalk'),
  ('lever','coderpad','Coderpad'),
  ('lever','contentsquare','Contentsquare'),
  ('lever','coupa','Coupa'),
  ('lever','cred','Cred'),
  ('lever','deputy','Deputy'),
  ('lever','dexterity','Dexterity'),
  ('lever','dlocal','Dlocal'),
  ('lever','docsumo','Docsumo'),
  ('lever','dreamgames','Dream Games'),
  ('lever','drivetrain','Drivetrain'),
  ('lever','dwolla','Dwolla'),
  ('lever','educative','Educative'),
  ('lever','entrata','Entrata'),
  ('lever','exowatt','Exowatt'),
  ('lever','factor','Factor'),
  ('lever','filevine','Filevine'),
  ('lever','finch','Finch'),
  ('lever','findigs','Findigs'),
  ('lever','finix','Finix'),
  ('lever','fresha','Fresha'),
  ('lever','gohighlevel','Gohighlevel'),
  ('lever','gopuff','Gopuff'),
  ('lever','gravie','Gravie'),
  ('lever','gynger','Gynger'),
  ('lever','immutable','Immutable'),
  ('lever','influ2','Influ2'),
  ('lever','jamcity','Jam City'),
  ('lever','kapwing','Kapwing'),
  ('lever','kasada','Kasada'),
  ('lever','kixie','Kixie'),
  ('lever','kochava','Kochava'),
  ('lever','ledger','Ledger'),
  ('lever','levelai','Level Ai'),
  ('lever','livingcarbon','Living Carbon'),
  ('lever','loadsmart','Loadsmart'),
  ('lever','loftorbital','Loft Orbital'),
  ('lever','logrocket','Logrocket'),
  ('lever','lyrahealth','Lyra Health'),
  ('lever','metabase','Metabase'),
  ('lever','mindtickle','Mindtickle'),
  ('lever','mistplay','Mistplay'),
  ('lever','mistral','Mistral'),
  ('lever','neighbor','Neighbor'),
  ('lever','neon','Neon'),
  ('lever','netomi','Netomi'),
  ('lever','offchainlabs','Offchain Labs'),
  ('lever','omnidian','Omnidian'),
  ('lever','omnisend','Omnisend'),
  ('lever','osaro','Osaro'),
  ('lever','our-place','Our Place'),
  ('lever','outreach','Outreach'),
  ('lever','padsplit','Padsplit'),
  ('lever','palantir','Palantir'),
  ('lever','peakgames','Peak Games'),
  ('lever','people-ai','People Ai'),
  ('lever','picklerobot','Pickle Robot'),
  ('lever','pigment','Pigment'),
  ('lever','pipedrive','Pipedrive'),
  ('lever','playbook','Playbook'),
  ('lever','porter','Porter'),
  ('lever','q-ctrl','Q-ctrl'),
  ('lever','qonto','Qonto'),
  ('lever','relay','Relay'),
  ('lever','restaurant365','Restaurant365'),
  ('lever','retro','Retro'),
  ('lever','rigetti','Rigetti'),
  ('lever','rise','Rise'),
  ('lever','ro','Ro'),
  ('lever','safe','Safe'),
  ('lever','sanabenefits','Sana Benefits'),
  ('lever','saviynt','Saviynt'),
  ('lever','scaleway','Scaleway'),
  ('lever','sesame','Sesame'),
  ('lever','shieldai','Shield Ai'),
  ('lever','shiru','Shiru'),
  ('lever','sila','Sila'),
  ('lever','spreedly','Spreedly'),
  ('lever','swapcard','Swapcard'),
  ('lever','swordhealth','Sword Health'),
  ('lever','sysdig','Sysdig'),
  ('lever','teller','Teller'),
  ('lever','theorycraftgames','Theorycraft Games'),
  ('lever','tinybird','Tinybird'),
  ('lever','tovala','Tovala'),
  ('lever','twingate','Twingate'),
  ('lever','unify','Unify'),
  ('lever','vendavo','Vendavo'),
  ('lever','voodoo','Voodoo'),
  ('lever','waabi','Waabi'),
  ('lever','wealthfront','Wealthfront'),
  ('lever','xcimer','Xcimer'),
  ('lever','yardzen','Yardzen'),
  ('lever','zeta','Zeta'),
  ('lever','zilliz','Zilliz'),
  ('lever','zushealth','Zus Health')
on conflict (platform, slug) do nothing;

-- Rotation cursor: leave last_ingested_at NULL so the hourly batch picks these
-- up first (order by last_ingested_at nulls first).
notify pgrst, 'reload schema';
