-- Bulk CC-harvested company boards, part 5/5 (33 rows).
insert into public.job_sources (platform, slug, company_name, datacenter, site) values
 ('workday','unitingcareqld','unitingcareqld','wd105','unitingcarecareers'),
 ('workday','uoh','uoh','wd103','University_of_Hull_Careers'),
 ('workday','uottawa','uottawa','wd3','uOttawa_External_Career_Site'),
 ('workday','uq','uq','wd3','uqopportunities'),
 ('workday','utampa','utampa','wd1','Staff'),
 ('workday','uva','uva','wd1','UVAStudentJobs'),
 ('workday','valeo','valeo','wd3','valeo_jobs'),
 ('workday','valmont','valmont','wd1','ValmontCareers'),
 ('workday','vanderlande','vanderlande','wd3','TALExternalCareers'),
 ('workday','vantiva','vantiva','wd103','vantiva'),
 ('workday','velux','velux','wd3','Velux_Residential'),
 ('workday','veradigm','veradigm','wd12','VR'),
 ('workday','veripark','veripark','wd103','veripark'),
 ('workday','vertexinc','vertexinc','wd1','VertexInc'),
 ('workday','vizient','vizient','wd1','Vizient_Careers'),
 ('workday','volarisgroup','volarisgroup','wd3','SparkTSL'),
 ('workday','wcbalberta','wcbalberta','wd10','wcbalbertacareers'),
 ('workday','webcotube','webcotube','wd12','Webco'),
 ('workday','weir','weir','wd3','weir_external_careers'),
 ('workday','wellesley','wellesley','wd1','wellesley-staff'),
 ('workday','wellsky','wellsky','wd1','wellskycareers'),
 ('workday','wework','wework','wd1','WeWork'),
 ('workday','wilburellis','wilburellis','wd12','WILBUR-ELLIS'),
 ('workday','wilhelmsen','wilhelmsen','wd3','Wilhelmsen'),
 ('workday','wlt','wlt','wd3','wl_careers'),
 ('workday','wolseleyuk','wolseleyuk','wd3','Wolseley'),
 ('workday','wonderbox','wonderbox','wd3','WONDERBOX_GROUP_CAREERS'),
 ('workday','worldacceptance','worldacceptance','wd12','World_Finance'),
 ('workday','wwwinc','wwwinc','wd1','www'),
 ('workday','ymcaatlanta','ymcaatlanta','wd1','YMCA-Careers'),
 ('workday','zeissgroup','zeissgroup','wd3','External'),
 ('workday','zentiva','zentiva','wd3','Zentiva'),
 ('workday','zuehlke','zuehlke','wd3','Zuhlke-Careers')
on conflict (platform, slug) do nothing;
